# Generated by Django 4.2.6 on 2023-10-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
